In [27]:
import quandl

In [119]:
quandl.ApiConfig.api_key = "dygSncwD1VTudYKz9UNb"
mydata = quandl.get("WIKI/MMM", start_date='2017-01-01')
mydata

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2017-01-03,178.83,180.0000,177.2200,178.05,2510055.0,0.0,1.0,175.597845,176.746699,174.016944,174.831943,2510055.0
2017-01-04,178.03,178.9000,177.6100,178.32,1541985.0,0.0,1.0,174.812305,175.666580,174.399896,175.097063,1541985.0
2017-01-05,178.26,179.1400,176.8900,177.71,1447568.0,0.0,1.0,175.038148,175.902243,173.692909,174.498088,1447568.0
2017-01-06,177.29,178.6000,175.8000,178.23,1625049.0,0.0,1.0,174.085679,175.372002,172.622609,175.008690,1625049.0
2017-01-09,178.37,178.3800,177.2000,177.27,1622625.0,0.0,1.0,175.146159,175.155979,173.997306,174.066041,1622625.0
2017-01-10,177.36,177.4900,176.3101,176.58,2030149.0,0.0,1.0,174.154414,174.282064,173.123490,173.388512,2030149.0
2017-01-11,176.63,178.4500,176.3900,177.89,1579593.0,0.0,1.0,173.437608,175.224714,173.201946,174.674835,1579593.0
2017-01-12,176.97,177.7000,175.7500,177.44,1321766.0,0.0,1.0,173.771463,174.488269,172.573513,174.232968,1321766.0
2017-01-13,177.58,177.9100,176.8300,177.39,1265593.0,0.0,1.0,174.370438,174.694473,173.633993,174.183872,1265593.0
2017-01-17,177.00,177.6800,176.2500,177.26,1557453.0,0.0,1.0,173.800921,174.468630,173.064476,174.056221,1557453.0
2017-01-18,177.90,179.4400,177.3800,178.49,1804904.0,0.0,1.0,174.684654,176.196820,174.174053,175.263991,1804904.0
2017-01-19,179.25,179.8000,177.7600,178.68,1464364.0,0.0,1.0,176.010254,176.550314,174.547185,175.450557,1464364.0
2017-01-20,179.20,179.4600,177.8300,178.49,1761780.0,0.0,1.0,175.961158,176.216459,174.615919,175.263991,1761780.0
2017-01-23,177.91,178.9900,177.1300,178.51,1986783.0,0.0,1.0,174.694473,175.754954,173.928571,175.283629,1986783.0
2017-01-24,177.50,177.7600,174.4200,175.97,3473183.0,0.0,1.0,174.291884,174.547185,171.267551,172.789537,3473183.0
2017-01-25,177.09,178.6300,176.5700,176.73,3462633.0,0.0,1.0,173.889294,175.401460,173.378692,173.535801,3462633.0
2017-01-26,176.31,177.2300,176.0400,176.82,2233979.0,0.0,1.0,173.123392,174.026764,172.858272,173.624174,2233979.0
2017-01-27,177.48,177.9800,176.8300,177.48,1623666.0,0.0,1.0,174.272245,174.763208,173.633993,174.272245,1623666.0
2017-01-30,177.25,177.7300,174.8700,175.42,1823128.0,0.0,1.0,174.046402,174.517727,171.709418,172.249477,1823128.0
2017-01-31,174.74,175.4600,173.8100,174.82,1845467.0,0.0,1.0,171.581768,172.288754,170.668576,171.660322,1845467.0
2017-02-01,175.17,175.8000,174.3000,175.17,2272854.0,0.0,1.0,172.003996,172.622609,171.149720,172.003996,2272854.0
2017-02-02,174.13,174.7750,173.5500,174.18,3106798.0,0.0,1.0,170.982793,171.616135,170.413276,171.031889,3106798.0
2017-02-03,174.02,175.3000,173.8500,175.04,2820960.0,0.0,1.0,170.874781,172.131646,170.707853,171.876345,2820960.0
2017-02-06,174.12,176.2000,173.9000,175.10,1622756.0,0.0,1.0,170.972973,173.015380,170.756950,171.935261,1622756.0
2017-02-07,176.08,176.4000,175.1539,175.76,1247189.0,0.0,1.0,172.897549,173.211765,171.988187,172.583332,1247189.0
2017-02-08,175.62,177.6000,175.4900,177.07,2145683.0,0.0,1.0,172.445863,174.390076,172.318212,173.869655,2145683.0
2017-02-09,176.87,178.5500,176.8700,178.18,2009742.0,0.0,1.0,173.673270,175.322906,173.673270,174.959593,2009742.0
2017-02-10,178.30,179.5800,178.1900,179.00,1392438.0,0.0,1.0,175.077425,176.334290,174.969413,175.764773,1392438.0
2017-02-13,179.86,181.3800,179.2600,181.02,1929821.0,0.0,1.0,176.609229,178.101757,176.020074,177.748264,1929821.0
2017-02-14,180.86,182.0000,180.6500,181.60,2036188.0,0.0,1.0,177.591155,178.710551,177.384951,178.317781,2036188.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2017-10-09,215.96,217.2100,215.6900,216.68,1053512.0,0.0,1.0,215.960000,217.210000,215.690000,216.680000,1053512.0
2017-10-10,217.38,217.6000,216.5500,216.75,1170940.0,0.0,1.0,217.380000,217.600000,216.550000,216.750000,1170940.0
2017-10-11,216.75,216.8600,214.6600,216.51,2016870.0,0.0,1.0,216.750000,216.860000,214.660000,216.510000,2016870.0
2017-10-12,216.60,217.6400,216.2900,217.59,1894038.0,0.0,1.0,216.600000,217.640000,216.290000,217.590000,1894038.0
2017-10-13,218.83,219.7600,216.8000,217.72,1461599.0,0.0,1.0,218.830000,219.760000,216.800000,217.720000,1461599.0
2017-10-16,217.70,218.7300,217.2000,218.72,1183691.0,0.0,1.0,217.700000,218.730000,217.200000,218.720000,1183691.0
2017-10-17,218.49,218.7200,216.4700,217.75,1875111.0,0.0,1.0,218.490000,218.720000,216.470000,217.750000,1875111.0
2017-10-18,217.52,218.6400,217.3700,218.27,1413576.0,0.0,1.0,217.520000,218.640000,217.370000,218.270000,1413576.0
2017-10-19,218.49,219.2500,217.4700,219.24,1359787.0,0.0,1.0,218.490000,219.250000,217.470000,219.240000,1359787.0
2017-10-20,219.95,221.3200,219.1900,221.32,1624470.0,0.0,1.0,219.950000,221.320000,219.190000,221.320000,1624470.0
2017-10-23,221.76,222.7800,221.2000,221.55,1962708.0,0.0,1.0,221.760000,222.780000,221.200000,221.550000,1962708.0
2017-10-24,229.00,238.9000,228.9900,234.65,6434602.0,0.0,1.0,229.000000,238.900000,228.990000,234.650000,6434602.0
2017-10-25,235.01,237.9400,233.9400,237.92,3404073.0,0.0,1.0,235.010000,237.940000,233.940000,237.920000,3404073.0
2017-10-26,238.26,238.8000,232.3100,232.94,3346878.0,0.0,1.0,238.260000,238.800000,232.310000,232.940000,3346878.0
2017-10-27,234.23,234.9500,232.5500,234.74,1988609.0,0.0,1.0,234.230000,234.950000,232.550000,234.740000,1988609.0
2017-10-30,233.66,233.6600,230.6400,231.02,2720504.0,0.0,1.0,233.660000,233.660000,230.640000,231.020000,2720504.0
2017-10-31,231.38,231.5975,229.8100,230.19,1891791.0,0.0,1.0,231.380000,231.597500,229.810000,230.190000,1891791.0
2017-11-01,231.00,231.7600,229.1100,230.18,1375491.0,0.0,1.0,231.000000,231.760000,229.110000,230.180000,1375491.0
2017-11-02,230.24,232.8000,229.5500,232.23,1579989.0,0.0,1.0,230.240000,232.800000,229.550000,232.230000,1579989.0
2017-11-03,231.56,232.5800,230.9200,232.22,1531962.0,0.0,1.0,231.560000,232.580000,230.920000,232.220000,1531962.0
2017-11-06,232.22,232.6300,230.1500,230.31,1334651.0,0.0,1.0,232.220000,232.630000,230.150000,230.310000,1334651.0
2017-11-07,230.38,230.7700,229.1400,230.05,1550074.0,0.0,1.0,230.380000,230.770000,229.140000,230.050000,1550074.0
2017-11-09,228.54,229.4000,227.0500,228.39,1568596.0,0.0,1.0,228.540000,229.400000,227.050000,228.390000,1568596.0
2017-11-15,228.07,228.5100,226.0400,227.40,1490293.0,0.0,1.0,228.070000,228.510000,226.040000,227.400000,1490293.0
2017-11-17,228.43,229.9200,227.7400,229.36,1732091.0,0.0,1.0,228.430000,229.920000,227.740000,229.360000,1732091.0
2017-11-20,229.90,233.5900,229.5543,231.49,1692009.0,0.0,1.0,229.900000,233.590000,229.554300,231.490000,1692009.0
2017-11-21,232.21,235.7100,232.2100,234.09,2035058.0,0.0,1.0,232.210000,235.710000,232.210000,234.090000,2035058.0
2017-11-27,231.75,234.5289,231.1300,234.00,1774883.0,0.0,1.0,231.750000,234.528900,231.130000,234.000000,1774883.0
2017-11-28,234.12,235.9400,233.3750,235.63,1797384.0,0.0,1.0,234.120000,235.940000,233.375000,235.630000,1797384.0
2017-12-05,240.22,240.2600,237.8600,238.26,1543134.0,0.0,1.0,240.220000,240.260000,237.860000,238.260000,1543134.0

In [120]:
for row in mydata:
    print(row)
    break

Open

In [129]:
mydata.empty
# dic = mydata.to_dict('index')
mydata.index.min()

Timestamp('2017-01-03 00:00:00')

In [58]:
for key, his in dic.items():
    print (key)
    break

1980-12-12 00:00:00

In [93]:
import datetime
import pandas as pd
from pandas.tseries.offsets import BDay

TBD1 = pd.datetime.today() - BDay(1)
tbd = TBD1.to_pydatetime().date()

In [98]:
from datetime import timedelta
tbd + timedelta(days=1)

datetime.date(2018, 1, 27)

In [135]:
print("""  ! Got error when dumping : {0}, error : {1}""".format('aaa', """bb with \'some strange strings\''"""))

  ! Got error when dumping : aaa, error : bb with 'some strange strings''

In [167]:
import mysql.connector
cnx = mysql.connector.connect(user='michael', password='Password2017',
                              host='localhost',
                              database='stock_market')
cnx.autocommit = True
cur = cnx.cursor()
# cur.execute("select * from `ops.operation_log` limit 10")
cur.execute("INSERT INTO `stock_market`.`ops.operation_log` (`effective_date`, `service_name`, `action_name`, `serverity`, `log_message`) VALUES  ( current_date, 'test service', 'test action', %s, %s)", ('T',"'test 'message"))
# [row[0] for row in cur.fetchall()]
# cnx.commit()

In [162]:
!where python

C:\Program Files\Python36\python.exe

In [164]:
!where pip3

INFO: Could not find files for the given pattern(s).

In [166]:
!python -m pip install mysql-connector==2.1.6

Requirement already satisfied: mysql-connector==2.1.6 in c:\program files\python36\lib\site-packages

In [170]:
import sys
# -*- coding: utf-8 -*-

# Print iterations progress
def print_progress(iteration, total, prefix='', suffix='', decimals=1, bar_length=100):
    """
    Call in a loop to create terminal progress bar

    @params:
        iteration   - Required  : current iteration (Int)
        total       - Required  : total iterations (Int)
        prefix      - Optional  : prefix string (Str)
        suffix      - Optional  : suffix string (Str)
        decimals    - Optional  : positive number of decimals in percent complete (Int)
        bar_length  - Optional  : character length of bar (Int)
    """
    str_format = "{0:." + str(decimals) + "f}"
    percents = str_format.format(100 * (iteration / float(total)))
    filled_length = int(round(bar_length * iteration / float(total)))
    bar = '█' * filled_length + '-' * (bar_length - filled_length)

    sys.stdout.write('\r%s |%s| %s%s %s' % (prefix, bar, percents, '%', suffix)),

    if iteration == total:
        sys.stdout.write('\n')
    sys.stdout.flush()

In [171]:
print_progress(10,100)

 |██████████------------------------------------------------------------------------------------------| 10.0%

In [173]:
import time,sys

for i in range(100+1):
    time.sleep(0.1)
    print_progress(i,100)
    #sys.stdout.write(('='*i)+(''*(100-i))+("\r [ %d"%i+"% ] "))
    #sys.stdout.flush()

 |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0%

In [7]:
import datetime
from datetime import timedelta
(datetime.date.today() + timedelta(days=-7)) .strftime('%Y%m%d')

'20180213'

In [9]:
tt = ('1', 2)
tt[1]

2